version: "3.4"

# Production environment override
services:
  php:
    environment:
      APP_SECRET: ${APP_SECRET}
      MERCURE_JWT_SECRET: ${CADDY_MERCURE_JWT_SECRET}

  caddy:
    environment:
      MERCURE_PUBLISHER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
      MERCURE_SUBSCRIBER_JWT_KEY: ${CADDY_MERCURE_JWT_SECRET}
    ports:
      # HTTP
      -   target: 80
          published: 81
          protocol: tcp
      # HTTPS
      -   target: 443
          published: 444
          protocol: tcp
      # HTTP/3
      -   target: 443
          published: 444
          protocol: udp
