controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute
    prefix:
        sk: '/' # don't prefix URLs for English, the default locale
        en: '/en'
